### ISSUE TITLE
SASO issue?

### ISSUE THREAD

**Issue by TeachRaccooon** [BallisticLA/RandBLAS#73]
Visible in [this ](https://github.com/BallisticLA/RandLAPACK/commit/4af3b03a2c271a9105c87ed5cde64312b9301da5) RandLAPACK commit.
I am recursively calling a randomized pivoted QR algorithm that employs SASOs for sketching.
At a certain point, we apply SASO to a matrix A with no visible anomalies, resulting in a sketchin with the last row consisting of zeros.
Upon performing QRCP on that sketch (via GEQP3), we get an R-factor with the last row consisting of zeros.
That, in its turn, causes NANs in subsequent computations. 
Seems to me like something may have gotten wrong with SASOs due to repeated usage of "state" parameter.

**Comment by rileyjmurray** [comment]
@TeachRaccooon is this potentially a real issue, or did this stem from a bug in non-RandBLAS code?

**Comment by TeachRaccooon** [comment]
@rileyjmurray I think this was happening because of me using the outdated version of RandBLAS.
Not an issue anymore.

**Comment by rileyjmurray** [comment]
Excellent. Closing for now.
